@extends('layouts.admin')

@section('title', 'Payroll Processing Details - ' . $monthName . ' ' . $year)

@section('content')
<div class="container-fluid px-0">

    <!-- Header & Back Navigation -->
    <div class="card border-0 shadow-sm mb-4">
        <div class="card-body p-3 p-md-4">
            <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3">
                <div class="d-flex align-items-center gap-3">
                    <a href="{{ route('payroll-processing.index') }}" class="btn btn-outline-secondary btn-sm p-2 rounded-circle d-flex align-items-center justify-content-center" style="width: 38px; height: 38px;" title="Back to Payroll Processing Dashboard">
                        <i class="bi bi-arrow-left fs-5"></i>
                    </a>
                    <div>
                        <h4 class="fw-bold mb-1 text-dark">Payroll Processing Details</h4>
                        <p class="text-secondary mb-0 small">
                            <span class="badge bg-primary me-2">{{ $monthName }} {{ $year }}</span>
                            Complete monthly status summary for Attendance, Payroll, and Salary Slips.
                        </p>
                    </div>
                </div>
                <div class="d-flex align-items-center gap-2">
                    <a href="{{ route('payroll-processing.index') }}" class="btn btn-secondary btn-sm">
                        <i class="bi bi-grid me-1"></i> Dashboard View
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- 3 Summary Cards Grid (Attendance, Payroll, Salary Slips) -->
    <div class="row g-3 mb-4">
        
        <!-- Section 1: Attendance Summary -->
        <div class="col-12 col-lg-4">
            <div class="card border-0 shadow-sm h-100">
                @php
                    $attNavUrl = $editAttendanceUrl;
                @endphp
                <div class="card-header bg-transparent border-0 pt-3 px-3 pb-0 d-flex justify-content-between align-items-center">
                    <a href="{{ $attNavUrl }}" class="d-flex align-items-center gap-2 text-decoration-none text-reset" style="cursor: pointer;" title="Click to view/manage Attendance">
                        <i class="bi bi-calendar-check text-success fs-5"></i>
                        <h6 class="fw-bold text-dark mb-0 link-primary">Attendance Summary</h6>
                    </a>
                    <a href="{{ $attNavUrl }}" class="text-decoration-none" style="cursor: pointer;">
                        @if($attendanceLocked)
                            <span class="badge bg-secondary-subtle text-secondary border border-secondary px-2 py-1"><i class="bi bi-lock-fill me-1"></i> Locked</span>
                        @elseif($attSummary['status'] === 'Completed' || $attSummary['status'] === 'In Progress')
                            <span class="badge bg-warning-subtle text-warning-emphasis border border-warning-subtle px-2 py-1">In Progress</span>
                        @else
                            <span class="badge bg-secondary-subtle text-secondary border border-secondary-subtle px-2 py-1">Pending</span>
                        @endif
                    </a>
                </div>
                <div class="card-body p-3 small d-flex flex-column justify-content-between">
                    <div>
                        <div class="row g-2 mb-2 pb-2 border-bottom border-light">
                            <div class="col-6">
                                <span class="text-muted d-block" style="font-size: 11px;">Generated By</span>
                                <span class="fw-semibold text-dark">{{ $attSummary['generated_by'] }}</span>
                            </div>
                            <div class="col-6">
                                <span class="text-muted d-block" style="font-size: 11px;">Generated Date</span>
                                <span class="fw-semibold text-dark">{{ $attSummary['generated_date'] }}</span>
                            </div>
                        </div>
                        <div class="row row-cols-2 g-2 text-center">
                            <div class="col">
                                <div class="p-2 bg-body-tertiary rounded">
                                    <span class="text-muted d-block" style="font-size: 11px;">Total Employees</span>
                                    <span class="fs-6 fw-bold text-dark">{{ $attSummary['total_employees'] }}</span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-2 bg-success-subtle rounded text-success">
                                    <span class="d-block" style="font-size: 11px;">Net Present</span>
                                    <span class="fs-6 fw-bold">{{ $attSummary['present_days'] }}</span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-2 bg-danger-subtle rounded text-danger">
                                    <span class="d-block" style="font-size: 11px;">Absent Days</span>
                                    <span class="fs-6 fw-bold">{{ $attSummary['absent_days'] }}</span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-2 bg-primary-subtle rounded text-primary">
                                    <span class="d-block" style="font-size: 11px;">Payable Days</span>
                                    <span class="fs-6 fw-bold">{{ $attSummary['payable_days'] }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mt-3 pt-2 border-top text-end">
                        @if(!$attendanceLocked)
                            <a href="{{ $editAttendanceUrl }}" id="btnEditAttendance" class="btn btn-sm btn-outline-primary fw-semibold">
                                <i class="bi bi-pencil me-1"></i> Edit Attendance
                            </a>
                        @else
                            <span class="badge bg-secondary-subtle text-secondary border border-secondary px-3 py-2 fs-6">
                                <i class="bi bi-lock-fill me-1"></i> Attendance Locked
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>

        <!-- Section 2: Payroll Summary -->
        <div class="col-12 col-lg-4">
            <div class="card border-0 shadow-sm h-100">
                @php
                    $payNavUrl = $hasPayroll ? route('payrolls.show', $payroll->id) : route('payrolls.create', ['month' => $month, 'year' => $year]);
                @endphp
                <div class="card-header bg-transparent border-0 pt-3 px-3 pb-0 d-flex justify-content-between align-items-center">
                    <a href="{{ $payNavUrl }}" class="d-flex align-items-center gap-2 text-decoration-none text-reset" style="cursor: pointer;" title="Click to view/manage Payroll">
                        <i class="bi bi-wallet2 text-primary fs-5"></i>
                        <h6 class="fw-bold text-dark mb-0 link-primary">Payroll Summary</h6>
                    </a>
                    <a href="{{ $payNavUrl }}" class="text-decoration-none" style="cursor: pointer;">
                        @if(in_array($paySummary['status'], ['Generated', 'Paid', 'Locked']))
                            <span class="badge bg-primary-subtle text-primary border border-primary-subtle px-2 py-1">{{ $paySummary['status'] }}</span>
                        @else
                            <span class="badge bg-warning-subtle text-warning-emphasis border border-warning-subtle px-2 py-1">Pending</span>
                        @endif
                    </a>
                </div>
                <div class="card-body p-3 small d-flex flex-column justify-content-between">
                    <div>
                        <div class="row g-2 mb-2 pb-2 border-bottom border-light">
                            <div class="col-6">
                                <span class="text-muted d-block" style="font-size: 11px;">Generated By</span>
                                <span class="fw-semibold text-dark">{{ $paySummary['generated_by'] }}</span>
                            </div>
                            <div class="col-6">
                                <span class="text-muted d-block" style="font-size: 11px;">Generated Date</span>
                                <span class="fw-semibold text-dark">{{ $paySummary['generated_date'] }}</span>
                            </div>
                        </div>
                        <div class="row row-cols-3 g-2 text-center">
                            <div class="col">
                                <div class="p-2 bg-body-tertiary rounded">
                                    <span class="text-muted d-block" style="font-size: 10px;">Gross Salary</span>
                                    <span class="fw-bold text-dark">₹ {{ number_format($paySummary['gross_salary'], 2) }}</span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-2 bg-danger-subtle rounded text-danger">
                                    <span class="d-block" style="font-size: 10px;">Deduction</span>
                                    <span class="fw-bold">₹ {{ number_format($paySummary['total_deduction'], 2) }}</span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-2 bg-success-subtle rounded text-success">
                                    <span class="d-block" style="font-size: 10px;">Net Salary</span>
                                    <span class="fw-bold">₹ {{ number_format($paySummary['net_salary'], 2) }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="mt-3 pt-2 border-top text-end">
                        @if($hasPayroll)
                            <a href="{{ route('payrolls.show', $payroll->id) }}" class="btn btn-sm btn-outline-info fw-semibold me-1">
                                <i class="bi bi-eye me-1"></i> View Payroll
                            </a>
                            @if(!$hasPayslip)
                                <a href="{{ route('payrolls.edit', $payroll->id) }}" id="btnEditPayroll" class="btn btn-sm btn-outline-primary fw-semibold">
                                    <i class="bi bi-pencil me-1"></i> Edit Payroll
                                </a>
                            @endif
                        @else
                            <span class="text-muted small">Payroll pending</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>

        <!-- Section 3: Salary Slip Summary -->
        <div class="col-12 col-lg-4">
            <div class="card border-0 shadow-sm h-100">
                @php
                    $slipNavUrl = $hasPayroll ? route('payroll-processing.show', [$year, $month]) : route('payrolls.create', ['month' => $month, 'year' => $year]);
                @endphp
                <div class="card-header bg-transparent border-0 pt-3 px-3 pb-0 d-flex justify-content-between align-items-center">
                    <a href="{{ $slipNavUrl }}" class="d-flex align-items-center gap-2 text-decoration-none text-reset" style="cursor: pointer;" title="Click to view/manage Salary Slips">
                        <i class="bi bi-file-earmark-text text-info fs-5"></i>
                        <h6 class="fw-bold text-dark mb-0 link-primary">Salary Slip Summary</h6>
                    </a>
                    <a href="{{ $slipNavUrl }}" class="text-decoration-none" style="cursor: pointer;">
                        @if($hasPayslip)
                            <span class="badge bg-info-subtle text-info border border-info-subtle px-2 py-1">Generated</span>
                        @else
                            <span class="badge bg-warning-subtle text-warning-emphasis px-2 py-1">Pending</span>
                        @endif
                    </a>
                </div>
                <div class="card-body p-3 small d-flex flex-column justify-content-between">
                    <div>
                        <div class="row row-cols-3 g-2 text-center mt-2">
                            <div class="col">
                                <div class="p-3 bg-body-tertiary rounded">
                                    <span class="text-muted d-block" style="font-size: 11px;">Total Employees</span>
                                    <span class="fs-5 fw-bold text-dark">{{ $slipSummary['total'] }}</span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-3 bg-info-subtle rounded text-info">
                                    <span class="d-block" style="font-size: 11px;">Generated</span>
                                    <span class="fs-5 fw-bold">{{ $slipSummary['generated'] }}</span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-3 bg-warning-subtle rounded text-warning">
                                    <span class="d-block" style="font-size: 11px;">Pending</span>
                                    <span class="fs-5 fw-bold">{{ $slipSummary['pending'] }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="mt-3 pt-2 border-top text-end">
                        @if($hasPayroll && !$hasPayslip)
                            <form action="{{ route('payroll-processing.generate-payslips', [$year, $month]) }}" method="POST" class="d-inline">
                                @csrf
                                <button type="submit" class="btn btn-sm btn-success fw-semibold">
                                    <i class="bi bi-file-earmark-plus me-1"></i> Generate Payslip
                                </button>
                            </form>
                        @elseif($hasPayslip)
                            <span class="badge bg-success-subtle text-success border border-success-subtle px-3 py-2 fs-6">
                                <i class="bi bi-check-circle-fill me-1"></i> Slips Active (View / Download below)
                            </span>
                        @else
                            <span class="text-muted small">Generate payroll first</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Section 4: Employee Breakdown Table -->
    <div class="card border-0 shadow-sm">
        <div class="card-header bg-transparent border-0 pt-3 px-4 pb-0 d-flex justify-content-between align-items-center">
            <h5 class="fw-bold text-dark mb-0">Employee Breakdown Table</h5>
            <span class="badge bg-secondary px-3 py-1">{{ count($employeeRows) }} Employees</span>
        </div>
        <div class="card-body p-0 mt-3">
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0 border-top">
                    <thead class="table-light">
                        <tr>
                            <th class="ps-4">Code</th>
                            <th>Employee Name</th>
                            <th>Department</th>
                            <th class="text-center">Attendance Status</th>
                            <th class="text-center">Payroll Status</th>
                            <th class="text-center">Salary Slip Status</th>
                            <th class="text-center pe-4">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($employeeRows as $row)
                            <tr>
                                <td class="ps-4 fw-semibold text-secondary">{{ $row['employee_code'] }}</td>
                                <td class="fw-bold text-dark">{{ $row['name'] }}</td>
                                <td class="text-secondary">{{ $row['department_name'] }}</td>
                                <td class="text-center">
                                    @if($row['attendance_status'] === 'Completed')
                                        <span class="badge bg-success-subtle text-success px-2 py-1">
                                            <i class="bi bi-check-circle me-1"></i> Present ({{ $row['payable_days'] }} days)
                                        </span>
                                    @else
                                        <span class="badge bg-warning-subtle text-warning-emphasis px-2 py-1">Pending</span>
                                    @endif
                                </td>
                                <td class="text-center">
                                    @if($row['payroll_status'] !== 'Pending')
                                        <span class="badge bg-primary-subtle text-primary px-2 py-1">
                                            <i class="bi bi-cash me-1"></i> {{ $row['payroll_status'] }}
                                        </span>
                                    @else
                                        <span class="badge bg-secondary-subtle text-secondary px-2 py-1">Pending</span>
                                    @endif
                                </td>
                                <td class="text-center">
                                    @if($row['salary_slip_status'] === 'Generated')
                                        <span class="badge bg-info-subtle text-info px-2 py-1">
                                            <i class="bi bi-file-earmark-check me-1"></i> Generated
                                        </span>
                                    @else
                                        <span class="badge bg-warning-subtle text-warning-emphasis px-2 py-1">Pending</span>
                                    @endif
                                </td>
                                <td class="text-center pe-4">
                                    @if($row['payroll_detail_id'] && $row['salary_slip_status'] === 'Generated')
                                        <div class="btn-group btn-group-sm" role="group">
                                            <a href="{{ route('payrolls.salary-slip', $row['payroll_detail_id']) }}" class="btn btn-outline-info" title="View Salary Slip" target="_blank">
                                                <i class="bi bi-eye me-1"></i> View
                                            </a>
                                            <a href="{{ route('payrolls.salary-slip.pdf', $row['payroll_detail_id']) }}" class="btn btn-outline-primary" title="Download Salary Slip PDF" target="_blank">
                                                <i class="bi bi-download me-1"></i> PDF
                                            </a>
                                        </div>
                                    @else
                                        <span class="text-muted small">Pending</span>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" class="text-center py-4 text-muted">
                                    No employee records found for this period.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const btnEditAttendance = document.getElementById('btnEditAttendance');
        if (btnEditAttendance) {
            btnEditAttendance.addEventListener('click', function (e) {
                if (!confirm("Editing attendance will affect payroll calculations. Do you want to continue?")) {
                    e.preventDefault();
                }
            });
        }

        const btnEditPayroll = document.getElementById('btnEditPayroll');
        if (btnEditPayroll) {
            btnEditPayroll.addEventListener('click', function (e) {
                const hasPayslips = {{ $hasPayslip ? 'true' : 'false' }};
                if (hasPayslips) {
                    if (!confirm("Editing payroll will invalidate existing salary slips. They will need to be regenerated. Do you want to continue?")) {
                        e.preventDefault();
                    }
                }
            });
        }
    });
</script>
@endpush
@endsection
